FROM knagadou/tensorflow-server:latest

RUN apt-get update && apt-get install -y \
        build-essential \
        curl \
        git \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        mlocate \
        pkg-config \
        python-dev \
        python-numpy \
        python-pip \
        python-wheel \
        software-properties-common \
        swig \
        zip \
        zlib1g-dev \
        libcurl3-dev \
        openjdk-8-jdk\
        openjdk-8-jre-headless \
        wget \
        iputils-ping \
        vim \
        net-tools \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install -U pip
RUN pip install mock grpcio requests google-cloud ipython[notebook] matplotlib

EXPOSE 80 8888 8080 443

CMD ["/bin/bash"]
