apiVersion: v1
kind: Service
metadata:
  labels:
    app: botserver
  name: loadbalancerbot
spec:
  ports:
  - name: jupyter
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: botserver
  sessionAffinity: None
  type: LoadBalancer
